import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "../../globals.css";
import Footer from "@/components/Footer";
import Sidebar from "@/components/dashboard/Sidebar";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // IMPORTANT
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-full flex">
      <Sidebar />
      
      <div className="flex-1 lg:ml-72">
        {children}
      </div>
    </div>
  );
}