'use client'
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar5 from "@/components/Navbar";
import { Provider } from "react-redux";
import { store } from "@/redux/store";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // IMPORTANT
  variable: "--font-roboto",
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* <Navbar5/> */}
        <Provider store={store}>{children}</Provider>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
